dialects:
  sybase:
    type_mappings:
      int: [integer, int4, int, serial]
      tinyint: [smallint, int2]
      smallint: [smallint, int2]
      bigint: [bigint, int8]
      varchar: [varchar, text, character varying]
      char: [char, character, bpchar]
      text: [text, varchar]
      nvarchar: [varchar, text]
      nchar: [char, character]
      datetime: [timestamp, timestamptz, timestamp with time zone]
      smalldatetime: [timestamp, timestamp without time zone]
      date: [date]
      time: [time, time without time zone]
      decimal: [numeric, decimal]
      numeric: [numeric, decimal]
      float: [real, double precision, float8, float4]
      real: [real, float4]
      double: [double precision, float8]
      money: [money, numeric]
      smallmoney: [money, numeric]
      bit: [boolean, bool]
      binary: [bytea]
      varbinary: [bytea]
      image: [bytea]
      uniqueidentifier: [uuid]
      xml: [xml, text]
      cursor: [refcursor]

    statement_mappings:
      RAISERROR: [RAISE]
      PRINT: [RAISE NOTICE]
      EXEC: [PERFORM, SELECT]
      BEGIN_TRAN: [BEGIN, TRY]
      COMMIT_TRAN: [COMMIT]
      ROLLBACK_TRAN: [ROLLBACK]
      CATCH: [EXCEPTION]
      DECLARE_CURSOR: [DECLARE CURSOR]
      OPEN_CURSOR: [OPEN]
      CLOSE_CURSOR: [CLOSE]
      DEALLOCATE_CURSOR: [CLOSE]
      BREAK: [EXIT]

  postgresql:
    type_mappings:
      integer: [int, int4, serial]
      smallint: [tinyint, smallint, int2]
      bigint: [bigint, int8]
      varchar: [nvarchar, text]
      text: [text, varchar]
      char: [char, nchar, character]
      timestamp: [datetime, smalldatetime]
      date: [date]
      time: [time]
      numeric: [decimal, numeric]
      real: [float, real, float4]
      double precision: [double, float8]
      money: [money, smallmoney, numeric]
      boolean: [bit, boolean, bool]
      bytea: [binary, varbinary, image]
      uuid: [uniqueidentifier]
      xml: [xml, text]
      refcursor: [cursor]

    statement_mappings:
      RAISE: [RAISERROR]
      RAISE NOTICE: [PRINT]
      PERFORM: [EXEC]
      SELECT: [EXEC]
      BEGIN: [BEGIN_TRAN, TRY]
      COMMIT: [COMMIT_TRAN]
      ROLLBACK: [ROLLBACK_TRAN]
      EXCEPTION: [CATCH]
      DECLARE CURSOR: [DECLARE_CURSOR]
      OPEN: [OPEN_CURSOR]
      CLOSE: [CLOSE_CURSOR, DEALLOCATE_CURSOR]
      EXIT: [BREAK]
